version: '3.7'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    expose:
      - 3000
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=8080
    ports:
      - 80:80
