export const DEFAULT_YEAR = "2023H1";

export const YEARS = {
    "2023H1": {
        groups: [
            {
                key: "lazarus_group",
                displayname: "Lazarus Group",
                bar: 35,
                width: "100%",
                map: ["KP"],
                mitre: {
                    code: "G0032",
                    url: "https://attack.mitre.org/groups/G0032/",
                },
                reports: [
                    {
                        url: "https://securelist.com/bluenoroff-methods-bypass-motw/108383",
                        title: "BlueNoroff introduces new methods bypassing MoTW",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.qualys.com/vulnerabilities-threat-research/2023/04/03/3cxdesktopapp-backdoored-in-a-suspected-lazarus-campaign",
                        title: "3CXDesktopApp Backdoored in a Suspected Lazarus Campaign",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/trustwave-action-response-supply-chain-attack-using-3cx-pbax-software",
                        title: "Trustwave Action Response: Supply Chain Attack Using 3CX PABX Software",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.welivesecurity.com/2023/04/20/linux-malware-strengthens-links-lazarus-3cx-supply-chain-attack",
                        title: "Linux malware strengthens links between Lazarus and the 3CX supply-chain attack",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://cybersecurity.att.com/blogs/labs-research/lazarus-campaign-ttps-and-evolution",
                        title: "Lazarus campaign TTPs and evolution",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/48416",
                        title: "Lazarus attack group attack case using public certificate software vulnerability widely used in public institutions and universities",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/en/48810",
                        title: "Lazarus Group Attack Case Using Vulnerability of Certificate Software Commonly Used by Public Institutions and Universities",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/52829",
                        title: "Lazarus Group Targeting Vulnerable Web Servers",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://medium.com/@dcso_cytec/andariels-jupiter-malware-and-the-case-of-the-curious-c2-dbfe29f57499",
                        title: "Andariels Jupiter malware and the case of the curious C2",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.mandiant.com/resources/blog/lightshow-north-korea-unc2970",
                        title: "Stealing the LIGHTSHOW (Part One) North Korea's UNC2970",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/53832",
                        title: "Lazarus attack group exploiting vulnerabilities in domestic financial security solutions",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.zscaler.com/security-research/coverage-advisory-3cx-supply-chain-attack-march-2023",
                        title: "Coverage Advisory for 3CX Supply Chain Attack",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.uptycs.com/blog/3cx-supply-chain-attack",
                        title: "3CX Supply Chain Cyber Attack: An Analysis of Windows and macOS Malicious Libraries",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://cloudsek.com/blog/technical-analysis-of-files-used-in-3cx-desktop-app-malware-campaign",
                        title: "Technical Analysis of Files Used in 3CX Desktop App Malware Campaign",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.volexity.com/blog/2023/03/30/3cx-supply-chain-compromise-leads-to-iconic-incident",
                        title: "3CX Supply Chain Compromise Leads to ICONIC Incident",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.crowdstrike.com/blog/crowdstrike-detects-and-prevents-active-intrusion-campaign-targeting-3cxdesktopapp-customers",
                        title: "CrowdStrike Falcon Platform Detects and Prevents Active Intrusion Campaign Targeting 3CXDesktopApp Customers",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/50797",
                        title: "3CX DesktopApp (CVE-2023-29059)",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/en/50919",
                        title: "Caution When Using 3CX DesktopApp (CVE-2023-29059)",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/50965",
                        title: "3CX DesktopApp supply chain attack confirmed in Korea",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.securonix.com/blog/security-advisory-3cx-smooth-operator-attack",
                        title: "Securonix Threat Labs Security Advisory: 3CX Smooth Operator Supply Chain Attack Business Impact and Detections",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://mp.weixin.qq.com/s/w4hkbrjnwn1g32qcpannoa",
                        title: "APT-C-26 lazarus",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/en/51090",
                        title: "3CX DesktopApp Supply Chain Attack Also Detected in Korea",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://wezard4u.tistory.com/6412",
                        title: "BlueNorOff targeting North Korean officials - Questionnaire.doc (2023.04.06)",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://securelist.com/the-lazarus-group-deathnote-campaign/109490",
                        title: "Following the Lazarus group by tracking DeathNote campaign",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/47820",
                        title: "Anti-forensic techniques used by the Lazarus group",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/47751",
                        title: "Distributed Malware Exploiting Vulnerable Innorix: Andariel",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://securelist.com/the-bluenoroff-cryptocurrency-hunt-is-still-on/105488/",
                        title: "The BlueNoroff cryptocurrency hunt is still on",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.qualys.com/vulnerabilities-threat-research/2022/02/08/lolzarus-lazarus-group-incorporating-lolbins-into-campaigns",
                        title: "LolZarus: Lazarus Group Incorporating Lolbins into Campaigns",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.malwarebytes.com/threat-intelligence/2022/01/north-koreas-lazarus-apt-leverages-windows-update-client-github-in-latest-campaign/",
                        title: "North Korea’s Lazarus APT leverages Windows Update client, GitHub in latest campaign",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/en/48198",
                        title: "Distribution of Malware Exploiting Vulnerable Innorix: Andariel",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.welivesecurity.com/2023/02/23/winordll64-backdoor-vast-lazarus-arsenal",
                        title: "WinorDLL64: A backdoor from the vast Lazarus arsenal?",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://wezard4u.tistory.com/6437",
                        title: "Word Malware-Interview.doc (2023.4.28) made by Lazarus that is believed to target the European Union (EU)",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.sekoia.io/bluenoroffs-rustbucket-campaign",
                        title: "Bluenoroff s RustBucket campaign",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blogs.jpcert.or.jp/en/2023/05/dangerouspassword.html",
                        title: "Attack Trends Related to DangerousPassword",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/en/53132",
                        title: "Lazarus Group Targeting Windows IIS Web Servers",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: [
                    "Labyrinth Chollima",
                    "Group 77",
                    "Hastati Group",
                    "Bureau 121",
                    "BeagleBoyzBureau121",
                    "Unit 121",
                    "Unit121",
                    "Whois Hacking Team",
                    "WHOis Team",
                    "NewRomanic Cyber Army Team",
                    "ZINC",
                    "APT-C-26",
                    "UNC2970",
                    "UNC577",
                    "UNC4736",
                    "Appleworm",
                    "NICKEL GLADSTONE",
                    "COVELLITE",
                    "ATK3",
                    "Hidden Cobra",
                    "Diamond Sleet",
                    "Black Artemis",
                    "Nickel Academy",
                    "LolZarus",
                    "G0032",
                ],
                active: "начиная с 2009",
                countries: [
                    {
                        displayname:
                            "Корейская Народно-Демократическая Республика",
                        code: "KP",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Финансовая мотивация",
                        code: "financially_motivated",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                targets:
                    "Lazarus Group атаковала организации из более чем 20 отраслей. </br>Большинство этих атак было направлено на организации промышленного сектора, работающие в финансовом, ИТ-секторе.",
            },
            {
                key: "kimsuky_group",
                displayname: "Kimsuky",
                bar: 21,
                width: "95%",
                map: ["KP"],
                mitre: {
                    code: "G0094",
                    url: "https://attack.mitre.org/groups/G0094/",
                },
                reports: [
                    {
                        url: "https://blog.malwarebytes.com/threat-intelligence/2022/01/konni-evolves-into-stealthier-rat/",
                        title: "KONNI evolves into stealthier RAT",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.lumen.com/new-konni-campaign-targeting-russian-ministry-of-foreign-affairs",
                        title: "New Konni Campaign Kicks Off The New Year By Targeting Russian Ministry Of Foreign Affairs",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://cluster25.io/wp-content/uploads/2022/01/konni_targeting_russian_diplomatic_sector.pdf",
                        title: 'North Korean group "Konni" targets the Russian diplomatic sector with new versions of malware implants',
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/49843",
                        title: "OneNote malware disguised as reward payment (Kimsuky)",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/50275",
                        title: "Kimsuky group distributes malware disguised as a profile file (GitHub)",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.alyac.co.kr/5043",
                        title: "Kimsuky organization, Kakao phishing attackMalware Analysis Report",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/47147",
                        title: "Malware disguised as a normal document (KIMSUKY)",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.sentinelone.com/labs/kimsuky-evolves-reconnaissance-capabilities-in-new-global-campaign",
                        title: "Kimsuky Evolves Reconnaissance Capabilities in New Global Campaign",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/52662",
                        title: "Kimsuky group using Meterpreter to attack web servers",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/48960",
                        title: "CHM malware (Kimsuky) disguised questionnaires related to North Korea",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.sentinelone.com/labs/kimsuky-ongoing-campaign-using-tailored-reconnaissance-toolkit",
                        title: "Kimsuky. Ongoing Campaign Using Tailored Reconnaissance Toolkit",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.sentinelone.com/labs/kimsuky-new-social-engineering-campaign-aims-to-steal-credentials-and-gather-strategic-intelligence",
                        title: "Kimsuky Strikes Again. New Social Engineering Campaign Aims to Steal Credentials and Gather Strategic Intelligence",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/en/50577",
                        title: "Overview of AhnLab s Response to Korea-Germany Joint Cyber Security Advice",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/en/45658",
                        title: "Malware Disguised as a Manuscript Solicitation Letter (Targeting Security-Related Workers)",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://wezard4u.tistory.com/6417",
                        title: "Word malware created by Kimsuky in North Korea-personal information.doc",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.zimperium.com/blog/kimsuky-infamous-threat-actor-churns-out-more-advanced-malware",
                        title: "Kimsuky: Infamous Threat Actor Churns Out More Advanced Malware",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://inquest.net/blog/2021/08/23/kimsuky-espionage-campaign",
                        title: "Kimsuky Espionage Campaign",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/en/31089/",
                        title: "Distribution of Kimsuky Group’s xRAT (Quasar RAT) Confirmed",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.proofpoint.com/us/resources/threat-reports/triple-threat-north-korea-aligned-ta406-scams-spies-and-steals",
                        title: "Triple Threat: North Korea Aligned TA406 Scams, Spies, and Steals",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/49964",
                        title: "Status of AhnLab Response to Korea-Germany Joint Cyber Security Advisory",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://asec.ahnlab.com/ko/50394",
                        title: "Kimsuky group uses ADS to hide malware",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: [
                    "Velvet Chollima",
                    "Kimsuky",
                    "Konni",
                    "Thallium",
                    "TA408",
                    "TA427",
                    "CloudDragon",
                    "TA406",
                    "SharpTongue",
                    "Crooked Pisces",
                    "Osmium",
                    "Cerium",
                    "Emerald Sleet",
                    "Black Banshee",
                    "APT43",
                    "Archipelago",
                    "Ruby Sleet",
                    "G0094",
                ],
                active: "начиная с 2012",
                countries: [
                    {
                        displayname:
                            "Корейская Народно-Демократическая Республика",
                        code: "KP",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Правительственные учреждения, аналитические центры, отдельные эксперты из Южной Кореи, США, России, Европпы и ООН.",
            },
            {
                key: "scarcruft_group",
                displayname: "ScarCruft",
                bar: 3,
                width: "60%",
                map: ["CHN"],
                mitre: {
                    code: "G0067",
                    url: "https://attack.mitre.org/groups/G0067/",
                },
                reports: [
                    {
                        url: "https://asec.ahnlab.com/ko/51628",
                        title: "RokRAT malware distributed through link files (*.lnk): RedEyes (ScarCruft)",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://research.checkpoint.com/2023/chain-reaction-rokrats-missing-link",
                        title: "Chain Reaction: ROKRAT s Missing Link",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://securelist.com/scarcruft-surveilling-north-korean-defectors-and-human-rights-activists/105074/",
                        title: "ScarCruft surveilling North Korean defectors and human rights activists",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: [
                    "Ricochet Chollima",
                    "Group 123",
                    "ScarCruft",
                    "APT37",
                    "Red Eyes",
                    "Reaper",
                    "Venus 121",
                    "THALLIUM",
                    "G0067",
                ],
                active: "начиная с 2012",
                countries: [
                    {
                        displayname:
                            "Корейская Народно-Демократическая Республика",
                        code: "KN",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Компании в Южной Корее, а также в Японии, Вьетнаме, России, Непале, Китае, Индии, Румынии, Кувейте и других частях Ближнего Востока.",
            },
            {
                key: "transparenttribe_group",
                displayname: "Transparent Tribe",
                bar: 12,
                width: "90%",
                map: ["PK"],
                mitre: {
                    code: "G0134",
                    url: "https://attack.mitre.org/groups/G0134/",
                },
                reports: [
                    {
                        url: "https://www.uptycs.com/blog/cyber_espionage_in_india_decoding_apt_36_new_linux_malware",
                        title: "Cyber Espionage in India: Decoding APT-36's New Linux Malware Campaign",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.cyble.com/2022/02/11/deep-dive-analysis-caprarat/",
                        title: "Deep Dive Analysis – capraRAT",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.trendmicro.com/en_us/research/22/a/investigating-apt36-or-earth-karkaddans-attack-chain-and-malware.html",
                        title: "Investigating APT36 or Earth Karkaddans Attack Chain and Malware Arsenal",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.welivesecurity.com/2023/03/07/love-scam-espionage-transparent-tribe-lures-indian-pakistani-officials",
                        title: "Love scam or espionage? Transparent Tribe lures Indian and Pakistani officials",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.sentinelone.com/labs/transparent-tribe-apt36-pakistan-aligned-threat-actor-expands-interest-in-indian-education-sector",
                        title: "Transparent Tribe (APT36). Pakistan-Aligned Threat Actor Expands Interest in Indian Education Sector",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://lab52.io/blog/new-transparentribe-operation-targeting-india-with-weaponized-covid-19-lure-documents/",
                        title: "New TransparenTribe Operation: Targeting India with weaponized COVID-19 lure documents",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://mp.weixin.qq.com/s/lvsragnmsl3a1jeuubuvyw",
                        title: "APT-C-56 Android RlmRat Linux.",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.malwarebytes.com/threat-intelligence/2021/12/sidecopy-apt-connecting-lures-to-victims-payloads-to-infrastructure/",
                        title: "SideCopy APT: Connecting lures to victims, payloads to infrastructure",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.talosintelligence.com/2021/07/sidecopy.html",
                        title: "InSideCopy: How this APT continues to evolve its arsenal",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://ti.qianxin.com/blog/articles/analysis-of-sidecopy-group's-recent-attacks-using-indian-ministry-of-defense-documents-as-lures-en",
                        title: "Analysis of SideCopy Group's Recent Attacks Using Indian Ministry of Defense Documents as Lures",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.team-cymru.com/post/allakore-d-the-sidecopy-train",
                        title: "AllaKore(d) the SideCopy Train",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://ti.qianxin.com/blog/articles/sidecopy-group-launches-attacks-on-india-using-a-new-trojan-en",
                        title: "Sidecopy Group Launches Attacks on India Using a New Trojan",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: [
                    "Mythic Leopard",
                    "ProjectM",
                    "APT36",
                    "Temp.Lapis",
                    "Copper Fieldstone",
                    "Green Havildar",
                    "APT-C-56",
                    "G0134",
                ],
                active: "начиная с 2013",
                countries: [
                    {
                        displayname: "Пакистан",
                        code: "PK",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Политическая мотивация",
                        code: "politically_motivated",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Дипломатические, оборонные и исследовательские организации в Индии и Афганистане.",
            },
            {
                key: "muddywater_group",
                displayname: "MuddyWater",
                bar: 8,
                width: "85%",
                map: ["IR"],
                mitre: {
                    code: "G0069",
                    url: "https://attack.mitre.org/groups/G0069/",
                },
                reports: [
                    {
                        url: "https://www.microsoft.com/en-us/security/blog/2023/04/07/mercury-and-dev-1084-destructive-attack-on-hybrid-environment",
                        title: "MERCURY and DEV-1084: Destructive attack on hybrid environment",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.group-ib.com/blog/muddywater-infrastructure",
                        title: "SimpleHarm: Tracking MuddyWater s infrastructure",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://mp.weixin.qq.com/s/aYB7W_elO4FHPUtKrUtzHQ",
                        title: "APT MuddyWater. APT organization Muddywater analysis",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.talosintelligence.com/2022/01/iranian-apt-muddywater-targets-turkey.html",
                        title: "Iranian APT MuddyWater targets Turkish users via malicious PDFs, executables",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://socradar.io/dark-web-profile-muddywater-apt-group",
                        title: "Dark Web Profile: MuddyWater APT Group",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://labs.k7computing.com/index.php/muddywater-back-with-darkbit",
                        title: "MuddyWater Back with DarkBit",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.sentinelone.com/labs/wading-through-muddy-waters-recent-activity-of-an-iranian-state-sponsored-threat-actor/",
                        title: "Wading Through Muddy Waters. Recent Activity of an Iranian State-Sponsored Threat Actor",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/espionage-campaign-telecoms-asia-middle-east",
                        title: "Espionage Campaign Targets Telecoms Organizations across Middle East and Asia",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: [
                    "TEMP.Zagros",
                    "Seedworm",
                    "Cobalt Ulster",
                    "SectorD02",
                    "MERCURY",
                    "MuddyWater",
                    "DarkBit",
                    "Mango Sandstorm",
                    "Boggy Serpens",
                    "ATK51",
                    "Static Kitten",
                    "Yellow nix",
                    "POWERSTATS",
                    "NTSTATS",
                    "G0069",
                ],
                active: "начиная с 2017",
                countries: [
                    {
                        displayname: "Иран",
                        code: "IR",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Государственные и частные организаций в различных секторах, включая телекоммуникации, органы власти, оборонную промышленность, а также нефтегазовые организации на Ближнем Востоке, в Азии, Африке, Европе и Северной Америке.",
            },
            {
                key: "gamaredon_group",
                displayname: "Gamaredon",
                bar: 6,
                width: "75%",
                map: ["RU"],
                mitre: {
                    code: "G0047",
                    url: "https://attack.mitre.org/groups/G0047/",
                },
                reports: [
                    {
                        url: "https://unit42.paloaltonetworks.com/trident-ursa/",
                        title: "Russias Trident Ursa (aka Gamaredon APT) Cyber Conflict Operations Unwavering Since Invasion of Ukraine",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blogs.blackberry.com/en/2023/01/gamaredon-abuses-telegram-to-target-ukrainian-organizations",
                        title: "Gamaredon (Ab)uses Telegram to Target Ukrainian Organizations",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.eclecticiq.com/three-cases-of-cyber-attacks-on-the-security-service-of-ukraine-and-nato-allies-likely-by-russian-state-sponsored-gamaredon",
                        title: "Three Cases of Cyber Attacks on the Security Service of Ukraine and NATO Allies, Likely by Russian State-Sponsored Gamaredon",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/shuckworm-gamaredon-espionage-ukraine",
                        title: "Shuckworm: Inside Russia s Relentless Cyber Campaign Against Ukraine",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.talosintelligence.com/following-the-lnk-metadata-trail",
                        title: "Following the LNK metadata trail",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.eclecticiq.com/exposed-web-panel-reveals-gamaredon-groups-automated-spear-phishing-campaigns",
                        title: "Exposed Web Panel Reveals Gamaredon Group's Automated Spear Phishing Campaigns",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: [
                    "Gamaredon Group",
                    "BlueAlpha",
                    "Shuckworm",
                    "ACTINIUM",
                    "Primitive Bear",
                    "Trident Ursa",
                    "Iron Tilden",
                    "G0047",
                ],
                active: "начиная с 2013",
                countries: [
                    {
                        displayname: "Россия",
                        code: "RU",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Военные, неправительственные, судебные, правоохранительные и некоммерческие организации в Украине.",
            },
            {
                key: "sidewinder_group",
                displayname: "SideWinder",
                bar: 7,
                width: "80%",
                map: ["IN"],
                mitre: {
                    code: "G0121",
                    url: "https://attack.mitre.org/groups/G0121/",
                },
                reports: [
                    {
                        url: "https://blogs.blackberry.com/en/2023/05/sidewinder-uses-server-side-polymorphism-to-target-pakistan",
                        title: "SideWinder Uses Server-side Polymorphism to Attack Pakistan Government Officials - and Is Now Targeting Turkey",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.group-ib.com/blog/hunting-sidewinder",
                        title: "The distinctive rattle of APT SideWinder",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://ti.qianxin.com/blog/articles/analysis-of-sidecopy-group's-recent-attacks-using-indian-ministry-of-defense-documents-as-lures-en",
                        title: "Analysis of SideCopy Group's Recent Attacks Using Indian Ministry of Defense Documents as Lures",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.cyble.com/2023/03/21/notorious-sidecopy-apt-group-sets-sights-on-indias-drdo",
                        title: "Notorious SideCopy APT group sets sights on India s DRDO",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.antiy.cn/research/notice&report/research_report/20230223.html",
                        title: "The Rattlesnake Group uses the theme of the epidemic to target my country's cyber attacks",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.team-cymru.com/post/allakore-d-the-sidecopy-train",
                        title: "AllaKore(d) the SideCopy Train",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: [
                    "SideWinder",
                    "APT-C-17",
                    "APT-Q-39",
                    "Hardcore Nationalist (HN2)",
                    "Rattlesnake",
                    "Razor Tiger",
                    "T-APT-04",
                    "G0121",
                ],
                active: "начиная с 2012",
                countries: [
                    {
                        code: "IN",
                        displayname: "Индия",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Правительственные, военные организации по всей Азии, в основном в Пакистане, Китае, Непале и Афганистане.",
            },
            {
                key: "magecart_group",
                displayname: "Magecart",
                bar: 6,
                width: "75%",
                map: [],
                mitre: {
                    code: "G0037",
                    url: "https://attack.mitre.org/groups/G0037/",
                },
                reports: [
                    {
                        url: "https://www.malwarebytes.com/blog/threat-intelligence/2023/01/crypto-inspired-magecart-skimmer-surfaces-via-digital-crime-haven",
                        title: "Crypto-inspired Magecart skimmer surfaces via digital crime haven",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.malwarebytes.com/blog/threat-intelligence/2023/03/hunter-skimmer",
                        title: "A look at a Magecart skimmer using the Hunter obfuscator",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.malwarebytes.com/blog/threat-intelligence/2023/03/new-kritec-skimmer",
                        title: "New Kritec Magecart skimmer found on Magento stores",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.malwarebytes.com/blog/threat-intelligence/2023/04/kritec-art",
                        title: "Magecart threat actor rolls out convincing modal forms",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.malwarebytes.com/blog/threat-intelligence/2023/02/multilingual-skimmer-fingerprints-users-via-cloudflare-endpoint-api",
                        title: "Multilingual skimmer fingerprints 'secret shoppers' via Cloudflare endpoint API",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.akamai.com/blog/security-research/new-magecart-hides-behind-legit-domains",
                        title: "New Magecart-Style Campaign Abusing Legitimate Websites to Attack Others",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: ["Skeleton Spider", "FIN6", "ITG08"],
                active: "начиная с 2015",
                countries: [],
                motivations: [
                    {
                        displayname: "Финансовая мотивация",
                        code: "financially_motivated",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Химическая промышленность, энергетика, гостиничный бизнес, розничная торговля.",
            },
            {
                key: "red_delta_group",
                displayname: "RedDelta",
                bar: 8,
                width: "85%",
                map: ["CN"],
                mitre: {
                    code: "G0129",
                    url: "https://attack.mitre.org/groups/G0129/",
                },
                reports: [
                    {
                        url: "https://www.welivesecurity.com/2023/03/02/mqsttang-mustang-panda-latest-backdoor-treads-new-ground-qt-mqtt",
                        title: "MQsTTang: Mustang Pandas latest backdoor treads new ground with Qt and MQTT",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://blog.eclecticiq.com/mustang-panda-apt-group-uses-european-commission-themed-lure-to-deliver-plugx-malware",
                        title: "Mustang Panda APT Group Uses European Commission-Themed Lure to Deliver PlugX Malware",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://labs.k7computing.com/index.php/mustang-panda-pe-injection-through-opera-mail",
                        title: "Mustang Panda PE Injection through Opera Mail",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://lab52.io/blog/new-mustang-pandas-campaing-against-australia",
                        title: "New Mustang Panda s campaing against Australia",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://lab52.io/blog/1943-2",
                        title: "Let s talk about the malware used by Mustang Panda",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.recordedfuture.com/reddelta-targets-european-government-organizations-continues-iterate-custom-plugx-variant",
                        title: "RedDelta Targets European Government Organizations and Continues to Iterate Custom PlugX Variant",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://research.checkpoint.com/2023/the-dragon-who-sold-his-camaro-analyzing-custom-router-implant",
                        title: "The Dragon Who Sold His Camaro: Analyzing Custom Router Implant. Key Findings",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://news.sophos.com/en-us/2023/03/09/border-hopping-plugx-usb-worm",
                        title: "A border-hopping PlugX USB worm takes its act on the road",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: [
                    "Mustang Panda",
                    "HoneyMyte",
                    "BRONZE PRESIDENT",
                    "Temp.Hex",
                    "TA416",
                    "RedDelta",
                    "Earth Preta",
                    "G0129",
                ],
                active: "начиная с 2015",
                countries: [
                    {
                        displayname: "Китай",
                        code: "CN",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Государственные учреждения, некоммерческие, религиозные и другие неправительственные организации в США, Европе, Монголии, Мьянме, Пакистане и Вьетнаме.",
            },
            {
                key: "teamtnt_group",
                displayname: "TeamTNT",
                bar: 2,
                width: "55%",
                map: [],
                mitre: {
                    code: "G0139",
                    url: "https://attack.mitre.org/groups/G0139/",
                },
                reports: [
                    {
                        url: "https://www.antiy.cn/research/notice&report/research_report/20221207.html",
                        title: "Typical mining family series analysis. TeamTNT mining organization",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.cadosecurity.com/previously-undiscovered-teamtnt-payload-recently-surfaced",
                        title: "Previously Undiscovered TeamTNT Payload Recently Surfaced",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: ["TeamTNT", "G0139"],
                active: "начиная с 2019",
                countries: [],
                motivations: [
                    {
                        displayname: "Финансовая мотивация",
                        code: "financially_motivated",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Развертывания майнеров криптовалюты в облачных средах жертв.",
            },
            {
                key: "donot_group",
                displayname: "Donot Team",
                bar: 4,
                width: "65%",
                map: [],
                mitre: {
                    code: "G0001",
                    url: "https://attack.mitre.org/groups/G0001/",
                },
                reports: [
                    {
                        url: "https://ti.qianxin.com/blog/articles/heavy-shadows:-summary-of-recent-attack-techniques-used-by-donot-group-en",
                        title: "Heavy Shadows: Summary of Recent Attack Techniques Used by Donot Group",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://labs.k7computing.com/index.php/the-donot-apt",
                        title: "The DoNot APT",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.cyfirma.com/outofband/donot-apt-targets-individuals-in-south-asia-using-android-malware",
                        title: "APT Bahamut Targets Individuals with Android Malware Using Spear Messaging",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://www.elastic.co/security-labs/elastic-security-labs-discovers-lobshot-malware",
                        title: "Elastic Security Labs discovers the LOBSHOT malware. Key takeaways",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: [
                    "Donot Team",
                    "APT-C-35",
                    "SectorE02",
                    "Lucky Elephant",
                ],
                active: "начиная с 2016",
                countries: [],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                    {
                        displayname: "Кража информации",
                        code: "information_theft",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Посольства, правительственные и оборонные предприятия в Аргентине, Бангладеше, Индии, Непале, Пакистане, Филиппинах, Шри-Ланке, Таиланде, Того, ОАЭ, Великобритании.",
            },
            {
                key: "axiom_group",
                displayname: "Axiom",
                bar: 2,
                width: "55%",
                map: ["CN"],
                mitre: {
                    code: "G0001",
                    url: "https://attack.mitre.org/groups/G0001/",
                },
                reports: [
                    {
                        url: "https://www.trendmicro.com/en_us/research/23/e/attack-on-security-titans-earth-longzhi-returns-with-new-tricks.html",
                        title: "Attack on Security Titans: Earth Longzhi Returns With New Tricks",
                        date: "01.01.2023",
                        icon: "",
                    },
                    {
                        url: "https://symantec-enterprise-blogs.security.com/threat-intelligence/blackfly-espionage-materials",
                        title: "Blackfly: Espionage Group Targets Materials Technology",
                        date: "01.01.2023",
                        icon: "",
                    },
                ],
                aliases: [
                    "Axiom",
                    "APT17",
                    "Tailgater Team",
                    "Group 72",
                    "Dogfish (iDefense)",
                    "Deputy Dog (iDefense)",
                    "Winnti Umbrella",
                    "G0001",
                ],
                active: "начиная с 2008",
                countries: [
                    {
                        displayname: "Китай",
                        code: "CN",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                    {
                        displayname: "Кража информации",
                        code: "information_theft",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Аэрокосмическая промышленность, оборонные предприятия, средства массовой информации в Японии, Южной Корее, Тайване, США.",
            },
            {
                key: "blindeagle_group",
                displayname: "Blind Eagle",
                bar: 6,
                width: "75%",
                map: [
                    "AR",
                    "BO",
                    "BR",
                    "VE",
                    "GF",
                    "CO",
                    "PY",
                    "PE",
                    "SR",
                    "UY",
                    "CL",
                    "EC",
                ],
                mitre: {
                    code: "G0099",
                    url: "https://attack.mitre.org/groups/G0099/",
                },
                reports: [
                    {
                        url: "https://mp.weixin.qq.com/s/mtmjlhyc9bjdnphf_52jma",
                        title: "APT-C-36. 1. Analysis of attack activities",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://lab52.io/blog/apt-c-36-from-njrat-to-apt-c-36",
                        title: "APT-C-36: from NjRAT to LimeRAT",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://research.checkpoint.com/2023/blindeagle-targeting-ecuador-with-sharpened-tools",
                        title: "BlindEagle Targeting Ecuador With Sharpened Tools.",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://mp.weixin.qq.com/s?__biz=mzuymjk4nzexma==&mid=2247492492&idx=1&sn=5cfd1606d6a3349c8cf0d8e1edba5c84&chksm=f9c1d085ceb65993c5e925e7eaeb91a9318a284573a42c36276f8c6c283ee10032e67fb4f47f&scene=178&cur_album_id=1955835290309230595#rd",
                        title: "APT-C-36 LimeRAT. 1. Affected situation",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://blogs.blackberry.com/en/2023/02/blind-eagle-apt-c-36-targets-colombia",
                        title: "Blind Eagle Deploys Fake UUE Files and Fsociety to Target Colombia's Judiciary, Financial, Public, and Law Enforcement Entities",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://ti.qianxin.com/blog/articles/subgroup-of-blind-eagle-analysis-of-recent-attack-activities-from-hagga-group-cn",
                        title: "Subgroup of the Blind Eagle? Analysis of recent attack activities from the Hagga organization",
                        icon: "",
                        date: "01.01.2023",
                    },
                ],
                aliases: ["Blind Eagle", "APT-C-36", "G0099"],
                active: "начиная с 2018",
                countries: [
                    {
                        displayname: "Аргентина",
                        code: "AR",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Боливия",
                        code: "BO",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Бразилия",
                        code: "BR",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Венесуэла",
                        code: "VE",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Гайана",
                        code: "GF",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Колумбия",
                        code: "CO",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Парагвай",
                        code: "PY",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Перу",
                        code: "PE",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Суринам",
                        code: "SR",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Уругвай",
                        code: "UY",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Чили",
                        code: "CL",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Эквадор",
                        code: "EC",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Государственные учреждения, а также на ключевые корпорации в финансовом секторе и нефтяной промышленности Колумбии.",
            },
            {
                key: "8220_gang_group",
                displayname: "8220 Gang",
                bar: 4,
                width: "65%",
                map: ["CN"],
                mitre: {},
                reports: [
                    {
                        url: "https://asec.ahnlab.com/ko/51362",
                        title: "8220 Gang Attack Group Installing Coin Miners Using Log4Shell Vulnerability Attack",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://www.trendmicro.com/en_us/research/23/e/8220-gang-evolution-new-strategies-adapted.html",
                        title: "8220 Gang Evolves With New Strategies",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://www.sentinelone.com/blog/soc-team-essentials-how-to-investigate-and-track-the-8220-gang-cloud-threat",
                        title: "SOC Team Essentials. How to Investigate and Track the 8220 Gang Cloud Threat",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://www.fortinet.com/blog/threat-research/old-cyber-gang-uses-new-crypter-scrubcrypt",
                        title: "Old Cyber Gang Uses New Crypter ScrubCrypt",
                        icon: "",
                        date: "01.01.2023",
                    },
                ],
                aliases: [
                    "Returned Libra",
                    "Mining Group",
                    "8220",
                    "8220 Gang",
                ],
                active: "начиная с 2017",
                countries: [
                    {
                        displayname: "Китай",
                        code: "CN",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Финансовая мотивация",
                        code: "financially_motivated",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets: "Уязвимые приложения и сервисы по всему миру.",
            },
            {
                key: "bitter_group",
                displayname: "Bitter",
                bar: 3,
                width: "60%",
                map: ["AF", "BD", "IN", "BT", "MV", "NP", "PK", "LK"],
                mitre: {
                    code: "G1002",
                    url: "https://attack.mitre.org/groups/G1002/",
                },
                reports: [
                    {
                        url: "https://asec.ahnlab.com/ko/50851",
                        title: "Bitter Group Spreads CHM Malware Targeting Chinese Institutions",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://mp.weixin.qq.com/s/h-zrvcofbzwz8ikyn5vu4w",
                        title: "Bitter Organization New Attack Weapon Analysis Report-ORPCBackdoor Weapon Analysis",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://www.intezer.com/blog/research/phishing-campaign-targets-nuclear-energy-industry",
                        title: "Phishing Campaign Targets Chinese Nuclear Energy Industry",
                        icon: "",
                        date: "01.01.2023",
                    },
                ],
                aliases: [
                    "Bitter",
                    "APT-C-08",
                    "Manling Flower (Manlinghua)",
                    "G1002",
                ],
                active: "начиная с 2013",
                countries: [
                    {
                        displayname: "Афганистан",
                        code: "AF",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Бангладеш",
                        code: "BD",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Бутан",
                        code: "BT",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Индия",
                        code: "IN",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Мальдивы",
                        code: "MV",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Непал",
                        code: "NP",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Пакистан",
                        code: "PK",
                        icon: "/path/to/img/icon2.png",
                    },
                    {
                        displayname: "Шри-Ланка",
                        code: "LK",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Правительственные, энергетические и инженерные организации в Пакистане, Китае, Бангладеш и Саудовской Аравии.",
            },
            {
                key: "killnet_group",
                displayname: "Killnet",
                bar: 5,
                width: "70%",
                map: ["RU"],
                mitre: {},
                reports: [
                    {
                        url: "https://cybersecurity.att.com/blogs/security-essentials/killnets-ddos-head-flood-attacks-cc.py",
                        title: "Threat Hunt: KillNet s DDoS HEAD Flood Attacks - cc\\.py",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://www.trendmicro.com/en_us/research/23/e/void-rabisu-s-use-of-romcom-backdoor-shows-a-growing-shift-in-th.html",
                        title: "Void Rabisu s Use of RomCom Backdoor Shows a Growing Shift in Threat Actors Goals",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/anonymous-sudan-religious-hacktivists-or-russian-front-group",
                        title: "SpiderLabs Blog. Anonymous Sudan: Religious Hacktivists or Russian Front Group?",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://medium.com/@lcam/updates-from-the-maas-new-threats-delivered-through-nullmixer-d45defc260d1",
                        title: "Updates from the MaaS: new threats delivered through NullMixer. Executive Summary",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://cyberknow.medium.com/killnet-2023-orbat-a9584d5c6e66",
                        title: "Killnet 2023 ORBAT",
                        icon: "",
                        date: "01.01.2023",
                    },
                ],
                aliases: [
                    "Killnet",
                    "Legion Spetsnaz RF",
                    "CYBER SPETSNAZ",
                    "Cyber Special Forces RF",
                    "Killmilk",
                    "Blackside",
                    "FasoninnGung",
                    "Sakurajima",
                    "Kratos",
                    "Phoenix squad",
                    "AKUR",
                    "XakNet",
                    "Legion",
                    "DDOSGUNG",
                    "Impulse",
                ],
                active: "начиная с 2022",
                countries: [
                    {
                        displayname: "Россия",
                        code: "RU",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Финансовая мотивация",
                        code: "financially_motivated",
                        icon: "/path/to/img/icon.png",
                    },
                    {
                        displayname: "Хактивизм",
                        code: "hacktivism",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Компании и государственные учреждения из стран НАТО и Украины.",
            },
            {
                key: "turla_group",
                displayname: "Turla Group",
                bar: 7,
                width: "80%",
                map: ["RU"],
                mitre: {
                    code: "G0010",
                    url: "https://attack.mitre.org/groups/G0010/",
                },
                reports: [
                    {
                        url: "https://www.mandiant.com/resources/blog/turla-galaxy-opportunity",
                        title: "Turla: A Galaxy of Opportunity",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://securelist.com/tomiris-called-they-want-their-turla-malware-back/109552",
                        title: "Tomiris called, they want their Turla malware back",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://blog.talosintelligence.com/threat-roundup-0106-0113",
                        title: "Cisco Talos Intelligence Blog. Threat Round up for January 6 to January 13",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://unit42.paloaltonetworks.com/turla-pensive-ursa-threat-assessment",
                        title: "Threat Group Assessment: Turla (aka Pensive Ursa). Additional References",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://www.welivesecurity.com/en/eset-research/moustachedbouncer-espionage-against-foreign-diplomats-in-belarus",
                        title: "MoustachedBouncer: Espionage against foreign diplomats in Belarus",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://socradar.io/apt-profile-turla",
                        title: "APT Profile: Turla",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-129a",
                        title: "Hunting Russian Intelligence Snake Malware",
                        icon: "",
                        date: "01.01.2023",
                    },
                ],
                aliases: [
                    "Turla Group",
                    "Snake",
                    "Venomous Bear",
                    "Group 88",
                    "Waterbug",
                    "Turla Team",
                    "Krypton",
                    "Uroburos",
                    "SIG23",
                    "MAKERSMARK",
                    "ITG12",
                    "IRON HUNTER",
                    "G0010",
                ],
                active: "начиная с 2004",
                countries: [
                    {
                        displayname: "Россия",
                        code: "RU",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Компании и учреждения из различных отраслей, включая правительства, посольства, военные, образовательные, исследовательские и фармацевтические компании по всему миру.",
            },
            {
                key: "aridviper_group",
                displayname: "AridViper",
                bar: 2,
                width: "55%",
                map: ["PS"],
                mitre: {},
                reports: [
                    {
                        url: "https://symantec-enterprise-blogs.security.com/threat-intelligence/mantis-palestinian-attacks",
                        title: "Mantis: New Tooling Used in Attacks Against Palestinian Targets",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://mp.weixin.qq.com/s?__biz=mzuymjk4nzexma==&mid=2247492294&idx=1&sn=305266e33cb615257c8a8c03df43e36a&chksm=f9c1d1cfceb658d947b30e2453ec96cfd1d608c17aebca6e74c8ca8ed11c187569b44538756a&scene=178&cur_album_id=1955835290309230595",
                        title: "APT-C-23. 1. Attack Action Analysis",
                        icon: "",
                        date: "01.01.2023",
                    },
                ],
                aliases: [
                    "AridViper",
                    "Desert Falcon",
                    "APT-C-23",
                    "Two-tailed Scorpion",
                ],
                active: "начиная с 2014",
                countries: [
                    {
                        displayname: "Палестина",
                        code: "PS",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Предполодительно располагается в Секторе Газа. Атакует правительственные организации, военные учреждения и компании в регионе Египета, Палестины, Иордании, ОАЭ, Израиля, Кувейта.",
            },
            {
                key: "carbanak_group",
                displayname: "Carbanak",
                bar: 4,
                width: "65%",
                map: ["UA"],
                mitre: {
                    code: "G0008",
                    url: "https://attack.mitre.org/groups/G0008/",
                },
                reports: [
                    {
                        url: "https://securityintelligence.com/posts/ex-conti-fin7-actors-collaborate-new-domino-backdoor",
                        title: "Ex-Conti and FIN7 Actors Collaborate with New Domino Backdoor",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://labs.withsecure.com/publications/fin7-target-veeam-servers",
                        title: "FIN7 tradecraft seen in attacks against Veeam backup servers",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://www.fortinet.com/blog/threat-research/ransomware-roundup-black-basta",
                        title: "Ransomware Roundup - Black Basta",
                        icon: "",
                        date: "01.01.2023",
                    },
                    {
                        url: "https://www.malwarebytes.com/blog/news/2023/04/malware-authors-join-forces-and-target-organisations-with-domino-backdoor",
                        title: "Malware authors join forces and target organisations with Domino Backdoor",
                        icon: "",
                        date: "01.01.2023",
                    },
                ],
                aliases: ["Anunak", "Carbanak", "Carbon Spider", "G0008"],
                active: "начиная с 2013",
                countries: [
                    {
                        displayname: "Украина",
                        code: "UA",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Киберкриминал",
                        code: "cyber_criminal",
                        icon: "/path/to/img/icon.png",
                    },
                    {
                        displayname: "Финансовая мотивация",
                        code: "financially_motivated",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets: "Банковские, платежные системы в России.",
            },
            {
                key: "duke_group",
                displayname: "The Dukes",
                bar: 1,
                width: "50%",
                map: ["RU"],
                mitre: {
                    code: "G0016",
                    url: "https://attack.mitre.org/groups/G0016/",
                },
                reports: [
                    {
                        url: "https://blogs.blackberry.com/en/2023/03/nobelium-targets-eu-governments-assisting-ukraine",
                        title: "NOBELIUM Uses Poland's Ambassadors Visit to the U.S. to Target EU Governments Assisting Ukraine",
                        icon: "",
                        date: "01.01.2023",
                    },
                ],
                aliases: [
                    "IRON RITUAL",
                    "IRON HEMLOCK",
                    "NobleBaron",
                    "Dark Halo",
                    "StellarParticle",
                    "NOBELIUM",
                    "UNC2452",
                    "YTTRIUM",
                    " The Dukes",
                    "Cozy Bear",
                    "CozyDuke",
                    "SolarStorm",
                    "Blue Kitsune",
                    "APT29",
                    "G0016",
                ],
                active: "начиная с 2008",
                countries: [
                    {
                        displayname: "Россия",
                        code: "RU",
                        icon: "/path/to/img/icon2.png",
                    },
                ],
                motivations: [
                    {
                        displayname: "Кибершпионаж",
                        code: "cyber_espionage",
                        icon: "/path/to/img/icon.png",
                    },
                ],
                targets:
                    "Компании и государственные учреждения, а также исследовательские институты и аналитические центры стран НАТО, США, Центральной Азии, Восточной Африки и нв Ближнем Востоке.",
            },
        ],
    },
};
